version: '2'
services:
    mediacenter-app:
        image: mediacenter
        external_links:
            - mediacenter-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/MediaCenter
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mediacenter-postgresql:
        extends:
            file: postgresql.yml
            service: mediacenter-postgresql
